-- 验证表结构
SHOW CREATE TABLE team\G
SHOW CREATE TABLE team_member\G

-- 验证索引已创建
SHOW INDEX FROM team;
SHOW INDEX FROM team_member;

-- 验证外键
SELECT CONSTRAINT_NAME, TABLE_NAME, REFERENCED_TABLE_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'zhihui' AND TABLE_NAME IN ('team', 'team_member');


SHOW CREATE TABLE meeting;
SHOW CREATE TABLE meeting_participant;
SHOW INDEX FROM meeting;
SHOW INDEX FROM meeting_participant;
-- 确认索引均已创建